- id: retino-prettier
  name: retino-prettier
  entry: prettier
  language: node
  files: \.html$
  args: ['--config=./src/.prettierrc', '--ignore-path=./src/.prettierignore']
  additional_dependencies:
    - prettier@3.1.0
    - '@prettier/plugin-xml@0.12.0'
    - eslint-config-prettier@8.3.0
    - eslint-plugin-prettier@4.0.0
    - prettier-plugin-tailwindcss@0.5.10
    - prettier-plugin-django-alpine@1.3.0
