- id: retino-prettier
  name: retino-prettier
  entry: retino-prettier
  language: node
  files: \.html$
  language_version: 16.13.0
  args: ['--config=./src/.prettierrc', '--ignore-path=./src/.prettierignore']
